<<<<<<< HEAD
language: java
install: true
script: "mvn install"
jdk:
  - oraclejdk8
=======
language: java
install: true
script: "mvn install"
jdk:
  - oraclejdk8
notifications:
  email: false
>>>>>>> 3e8b4f6b46df55a25ab9a29a2fa68ddb13b105a5
